---
name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/dependency-review.yml@19e378e0eccc844e49fb62d616c8ab99ace7fa6f # v2.3.0
