---
name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/dependency-review.yml@2a1d615a6636a64e016d57fb649d2fcc46ce501b # v3.0.0
