---
name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * 1"

permissions: {}

jobs:
  openssf-scorecard:
    name: OpenSSF Scorecard
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/openssf-scorecard.yml@201a2d1c4a2f70c53a8f33e99111efd292d446ab # v3.3.0
