---
name: Spell Check

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@f8eec741ffb11054c5d89cd7af91540cd36b0d2a # v3.4.3
