---
name: Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/super-linter.yml@201a2d1c4a2f70c53a8f33e99111efd292d446ab # v3.3.0
