---
name: Zizmor

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/zizmor.yml@201a2d1c4a2f70c53a8f33e99111efd292d446ab # v3.3.0
